# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f558b973805a402c40e2e72cc9e78a32dae8e7f33c7eb25f85fa8801ec39288f92ff96972905367f35c6dfdb797a44ebc817a54b3b23efe413bfbfda5080850

test:
  secret_key_base: a052b959df943f96c25b4c274c6ec1d16a7bb7f04d89ac7c485a3acf4661fcb43f5711bfaa8c954fd4f2a5b98db27ed31cc9a331e96afac5f7183044428bcece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
